export interface EventsList {
  CLEAR_QUEUE: string;
  CLIENT_DISCONNECTED: string;
  CLIENT_TYPE_IS_ALREADY_ONLINE: string;
  CONNECT: string;
  CONNECT_ERROR: string;
  DESKTOP_INIT: string;
  DISCONNECT: string;
  INTERNAL_SERVER_ERROR: string;
  NEW_CLIENT_CONNECTED: string;
  PLAY_NEXT: string;
  PLAY_PAUSE: string;
  PLAY_PREVIOUS: string;
  ROOM_STATUS: string;
  STOP_PLAYBACK: string;
  UPDATE_CURRENT_TRACK: string;
  UPDATE_LOOP: string;
  UPDATE_MUTE: string;
  UPDATE_PLAYBACK_STATE: string;
  UPDATE_PROGRESS: string;
  UPDATE_QUEUE: string;
  UPDATE_SHUFFLE: string;
  UPDATE_VOLUME: string;
};
